### ISSUE TITLE
When no posts on board, last post time is shown as "NaN seconds ago"

### ISSUE THREAD

**Issue by nteleky** [dggriffin/noteworthee#1]
![noteworthee-lastpost-bug](https://cloud.githubusercontent.com/assets/3300277/18279682/65d6fcb4-7424-11e6-8545-5dfdfafe73c2.PNG)

**Comment by dggriffin** [comment]
Ooops. Will fix. :+1:

**Comment by dggriffin** [comment]
Fixed.
